# Form implementation generated from reading ui file 'tool_widget.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(243, 320)
        self.buttonStart = QtWidgets.QPushButton(parent=Form)
        self.buttonStart.setGeometry(QtCore.QRect(80, 130, 75, 24))
        self.buttonStart.setObjectName("buttonStart")
        self.frameTool = QtWidgets.QFrame(parent=Form)
        self.frameTool.setGeometry(QtCore.QRect(-1, -1, 251, 321))
        self.frameTool.setStyleSheet("background-color:rgb(255, 255, 127);")
        self.frameTool.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameTool.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameTool.setObjectName("frameTool")
        self.labelAnswer = QtWidgets.QLabel(parent=Form)
        self.labelAnswer.setGeometry(QtCore.QRect(50, 201, 131, 16))
        self.labelAnswer.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelAnswer.setObjectName("labelAnswer")
        self.frameTool.raise_()
        self.buttonStart.raise_()
        self.labelAnswer.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.buttonStart.setText(_translate("Form", "click to start"))
        self.labelAnswer.setText(_translate("Form", "answer goes here"))
